apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
      - image: milomilon/auth:latest
        name: ms-auth
        ports:
          - containerPort: 9000
        env:
          - name: LB_USUARIOS_URI
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: lb_usuarios_uri
---

apiVersion: v1
kind: Service
metadata:
  name: ms-auth
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: ms-auth
  type: LoadBalancer