apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  db_database: ms_usuarios
#  username: root
#  password: admin
  cursos_url: ms-cursos:8002
  
  # Spring Cloud en ConfigMap
  ms-usuarios.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configuración de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configuración de producción  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  db_database: ms_cursos
#  username: postgres
#  password: admin
  usuarios_url: ms-usuarios:8001