apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios
  template:
    metadata:
      labels:
        app: ms-usuarios
    spec:
      containers:
      - image: milomilon/curso-kubernetes-usuarios:latest
        name: curso-kubernetes-usuarios
        ports:
          - containerPort: 8001
        env:
          - name: LB_AUTH_ISSUER_URI
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: lb_auth_issuer_uri
          - name: LB_USUARIOS_URI
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: lb_usuarios_uri
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: db_database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ms-usuarios
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-usuarios
                key: password
          - name: CURSOS_URL
            valueFrom:
              configMapKeyRef:
                name: ms-usuarios
                key: cursos_url
          # activamos el perfil dev      
          - name: SPRING_PROFILES_ACTIVE
            value: dev
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8001
#            scheme: HTTP
#          initialDelaySeconds: 5
#          periodSeconds: 20
#          timeoutSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8001
#            scheme: HTTP
#          initialDelaySeconds: 10
#          periodSeconds: 30
#          timeoutSeconds: 10
        #Asignar recursos a los pods
#        resources:
#          requests:
#            memory: "512Mi"
#            cpu: "400m"
#          limits:
#            memory: "800Mi"
#            cpu: "500m"        