apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cursos
  template:
    metadata:
      labels:
        app: ms-cursos
    spec:
      containers:
      - image: milomilon/curso-kubernetes-cursos:latest
        name: curso-kubernetes-cursos
        ports:
          - containerPort: 8002
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: ms-cursos
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ms-cursos
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: ms-cursos
                key: db_database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ms-cursos
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-cursos
                key: password
          - name: USUARIOS_URL
            valueFrom:
              configMapKeyRef:
                name: ms-cursos
                key: usuarios_url